#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

# ---- Generate public/index.html ----

rm -f public/index.html

echo "<html>" > public/index.html

echo "<h1>HTML Pages</h1>" >> public/index.html
find public/* -print | sed 's|^public\/||g' | sed 's/^.*/<a href="&">&<\/a><br\/>/' | grep ".html" | sort -r >> public/index.html

echo "<h1>CSS/SVG</h1>" >> public/index.html
find public/* -print | sed 's|^public\/||g' | sed 's/^.*/<a href="&">&<\/a><br\/>/' | grep -v ".html" | sort -r >> public/index.html

echo "</html>" >> public/index.html

cat public/index.html


# ---- Sync to S3 Bucket ----

bucket="nemoj-da-te-trazim.semaphoreci.com"
branch=$(git rev-parse --abbrev-ref HEAD | sed 's|\/|-|')
timestamp=$(ruby -e "puts Time.now.to_s.gsub(' ', '--').gsub(':', '-').gsub('+','')")
sha=$(git rev-parse --short HEAD)

aws s3 sync "public" "s3://$bucket/$timestamp-$branch-$sha" --acl "public-read"

echo "Uploaded to $bucket/$branch-$sha"


# ---- Regenerate index.html for the whole bucket ----

echo "<html>" > /tmp/index.html

echo "<h1>Master Branch</h1>" >> /tmp/index.html
aws s3 ls "$bucket" | grep "PRE" | awk '{ print $2 }' | sed 's/^.*/<a href="&">&<\/a><br\/>/' | grep "master" | sort -r >> /tmp/index.html

echo "<h1>Other Branches</h1>" >> /tmp/index.html
aws s3 ls "$bucket" | grep "PRE" | awk '{ print $2 }' | sed 's/^.*/<a href="&">&<\/a><br\/>/' | grep -v "master" | sort -r >> /tmp/index.html

echo "</html>" >> /tmp/index.html

aws s3 cp /tmp/index.html "s3://$bucket/index.html" --acl "public-read"
