#!/usr/bin/env bash
set -euo pipefail

bucket="semaphore-public-assets"

# 1. Upload new release

gsutil -h "Cache-Control:no-cache, max-age=0" cp -r public gs://$bucket

# 2. Grant Read access over the Internet

gsutil acl -R ch -u AllUsers:R gs://$bucket/public

# 3. Update index.html
touch index.html
echo "<html>" >> index.html
echo "<head></head>" >> index.html
echo "<body>" >> index.html
echo "<h1>Public Assets</h1>" >> index.html
gsutil ls -r gs://semaphore-public-assets/public | sed 's/gs:\//https:\/\/storage.googleapis.com/' | tail -n +2 | while read -r line; do echo "<a href='$line'>$line</a>"; done >> index.html
echo "</body>" >> index.html
echo "</html>" >> index.html


gsutil -h "Cache-Control:no-cache, max-age=0" cp index.html gs://$bucket
gsutil acl -R ch -u AllUsers:R gs://$bucket/

rm index.html

echo "Index of public assets -> https://storage.googleapis.com/semaphore-public-assets/index.html"
